# Ismail Ahmed: The initalizing file for the tox enviroment for all pytests
[tox]
envlist = py36, py38, py39, py310, py311, py312
isolated_build = true
skip_missing_interpreters = true

# Have to build pycryptodome from source wihtou its ABI3 to get it working with Python 3.12
[testenv]
setenv =
    PIP_NO_BINARY = :all:
    PIP_FORCE_REINSTALL = 1
    ; CRYPTOGRAPHY_DONT_BUILD_RUST = 1
    DISABLE_PYCRYPTODOME_ABI3 = 1
    PYCRYPTODOME_DISABLE_ABI3 = 1
deps =
    setuptools>=61.0
    wheel
    pytest>=7.0.0
    paramiko>=3.0.0
    pycryptodome>=3.18.0
; commands_pre =
;     python -c "import os, sys, platform; \
; from Crypto.Cipher import _mode_ecb as mod; \
; path = os.path.dirname(mod.__file__); \
; so_suffix = f'cpython-{sys.version_info[0]}{sys.version_info[1]}'; \
; files = os.listdir(path); \
; print(f'[ABI CHECK] looking in {path}'); \
; print(f'[ABI CHECK] found: {files}'); \
; so_matches = [f for f in files if f.endswith('.so')]; \
; if any(so_suffix in f for f in so_matches): \
;     print(f'[OK] Found ABI-specific .so for {so_suffix}'); \
; elif any('abi3' in f for f in so_matches): \
;     print('[ERROR] ABI3 .so detected – pycryptodome may fail to load'); \
;     sys.exit(1); \
; else: \
;     print('[ERROR] No pycryptodome .so file found – build likely failed'); \
;     sys.exit(2)"
commands =
    python -m unittest discover -s tests

; [testenv]
; setenv =
;     PIP_NO_BINARY = :all:
;     PIP_FORCE_REINSTALL = 1
; deps =
;     setuptools>=61.0
;     wheel
;     pytest>=7.0.0
;     pycryptodome>=3.18.0
;     paramiko>=3.0.0
; commands =
;     python -m unittest discover -s tests
